# Configuration related to a specific model.
# For syntax see: https://github.com/toml-lang/toml#table-of-contents


# Model specific common attributes.
[common]

  # Use CUDA for GPU acceleration.
  cuda       = false

  # Batch size for training.
  batch_size = 4

  # Image side size in pixels.
  image_size = 512

  # Directory where to save checkpoints to during training.
  checkpoint = '/tmp/pth/'


  classes = ["notvineyard", "vineyard"]
  colors = ["green", "red"]
  dataset="/home/sakthivm/vineyard_detection/robosat-master_3/vineyards/dataset"


# Model specific optimization parameters.
[opt]

  # Total number of epochs to train for.
  epochs     = 100

  # Learning rate for the optimizer.
  lr         = 0.0001

  # Loss function name (e.g 'Lovasz', 'mIoU' or 'CrossEntropy')
  loss = 'Lovasz'

# Dataset specific class weights computes on the training data.
# Needed by 'mIoU' and 'CrossEntropy' losses to deal with unbalanced classes.
# Note: use `./rs weights -h` to compute these for new datasets.
[weights]
  values = [1.927425, 3.252628]
